### ISSUE TITLE
Discovery funktioniert im Docker Container nicht

### ISSUE THREAD

**Issue by tkaufmann** [Nall-chan/Yeelight#7]
Hi, 

so starte ich IPS 5.5 im Docker Container unter Ubuntu 20.04: 

````
docker run --name symcon \
           --hostname symcon \
           --restart always \
           -d \
           -p 3777:3777 \
           -p 1982:1982/udp \
           -v /root/docker/symcon/symcon/data:/var/lib/symcon \
           -v /root/docker/symcon/symcon/log:/var/log/symcon \
           -v /root/docker/symcon/symcon:/root \
           symcon/symcon:stable
````

Das Discovery Modul sagt, es benötige noch eine Freigabe für Port 1982. Auf dem Host läuft keine Firewall. Liegt's an mir oder am Discovery-modul?

Liebe Grüße

Tim

**Comment by tkaufmann** [comment]
Beim aktivieren eines manuell hinzugefügten Client Sockets: 

<img width="1159" alt="SC-4" src="https://user-images.githubusercontent.com/871500/129239528-2c2f4aa8-956d-433f-951e-58f77d29faa7.png">

**Comment by Nall-chan** [comment]
Mir ist keine Lösung bekannt die Multicasts in docker zu empfangen, wenn der Container per NAT angebunden ist.
Nur mit net=host wird es wohl funktionieren.
https://stackoverflow.com/a/42425642

**Comment by tkaufmann** [comment]
Hi Michael, --net=host hat nichts gebracht. Hab symcon jetzt direkt auf dem Ubuntu laufen, auch hier der Fehler bezüglich Port 1982. Es ist ein Standard Server Install. Manuelles Hinzufügen scheint aber zu klappen, zumindest erstellt er mir jetzt Variablen und Änderungen über die App schlagen sich in der Anzeige in IPSymcon nieder.
